name: Release Verification Tests

on: workflow_call

jobs:
  prebuild-ubuntu:
    uses: ./.github/workflows/callable-prebuild-amplify-api-next.yml
    with:
      runs_on: ubuntu-latest
  # TODO: verify we can remove this:
  prebuild-macos:
    uses: ./.github/workflows/callable-prebuild-amplify-api-next.yml
    with:
      runs_on: macos-latest
  prebuild-samples-staging:
    secrets: inherit
    uses: ./.github/workflows/callable-prebuild-samples-staging.yml
  unit-tests:
    needs:
      - prebuild-ubuntu
    uses: ./.github/workflows/callable-unit-tests.yml
  e2e:
    needs:
      - prebuild-macos
      - prebuild-ubuntu
      - prebuild-samples-staging
    secrets: inherit
    uses: ./.github/workflows/callable-e2e-tests.yml
