name: Release Verification Tests

on: workflow_call

jobs:
  prebuild-ubuntu:
    uses: ./.github/workflows/callable-prebuild-amplify-data.yml
    with:
      runs_on: ubuntu-latest
  # prebuild-samples-staging:
  #   secrets: inherit
  #   uses: ./.github/workflows/callable-prebuild-samples-staging.yml
  # unit-tests:
  #   needs:
  #     - prebuild-ubuntu
  #   uses: ./.github/workflows/callable-unit-tests.yml
  # NOTE: "local-e2e" is a temporal naming to distinguish them from those pulled 
  # from amplify-js-samples-staging. Should be renamed once we move all e2e tests
  # to the amplify-data repo.
  local-e2e:
    needs:
      - prebuild-ubuntu
    secrets: inherit
    uses: ./.github/workflows/callable-local-e2e-tests.yml
  # e2e:
  #   needs:
  #     - prebuild-ubuntu
  #     - prebuild-samples-staging
  #   secrets: inherit
  #   uses: ./.github/workflows/callable-e2e-tests.yml
