name: Sandbox E2E Tests

on: workflow_call

jobs:
  sandbox_test:
    name: Sandbox E2E Tests
    runs-on: ubuntu-latest
    permissions:
      # these permissions are required for the configure-aws-credentials action to get a JWT from GitHub
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0 https://github.com/actions/checkout/commit/24cb9080177205b6e8c946b17badbe402adc938f
        with:
          path: amplify-api-next
      - name: Setup node and build the repository
        uses: ./amplify-api-next/.github/actions/node-and-build
      - name: Configure AWS test execution credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # version 4.0.2
        with:
          role-to-assume: ${{ secrets.SANDBOX_E2E_RUNNER_ROLE_ARN }}
          aws-region: us-west-2
      - name: Install Sandbox E2E Dependencies
        working-directory: ./amplify-api-next
        run: npm run e2e-sandbox:install
      - name: Run E2E sandbox tests
        working-directory: ./amplify-api-next
        run: npm run e2e-sandbox:test
