name: Sandbox E2E Tests

on: workflow_call

jobs:
  sandbox_test:
    name: Sandbox E2E Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0 https://github.com/actions/checkout/commit/24cb9080177205b6e8c946b17badbe402adc938f
        with:
          path: amplify-api-next
      - name: Setup node and build the repository
        uses: ./amplify-api-next/.github/actions/node-and-build
      # Separately, the backend team has an AWS profile that contains additional
      # test harness permissions which is configured here:
      - name: Configure test tooling credentials
        uses: ./.github/actions/setup_profile
        with:
          role-to-assume: ${{ secrets.E2E_TOOLING_ROLE_ARN }}
          aws-region: us-west-2
          profile-name: e2e-tooling
      # The CLI commands pick up credentials using the default credential provider
      # which resolves to the env vars that the `configure-aws-credentials` GitHub Action sets here:
      # This is loaded into various clients here: https://github.com/aws-amplify/amplify-backend/blob/f5eeb67d840a194ffeeb585bfa0ba9468c1f6cda/packages/integration-tests/src/test-project-setup/cdk/test_cdk_project_creator.ts#L30
      - name: Configure test execution credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # version 4.0.2
        with:
          role-to-assume: ${{ secrets.E2E_RUNNER_ROLE_ARN }}
          aws-region: us-west-2
      # - name: Configure AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@04b98b3f9e85f563fb061be8751a0352327246b0 # version 3.0.1
      #   with:
      #     role-to-assume: ${{ secrets.E2E_RUNNER_ROLE_ARN }}
      #     aws-region: us-west-2
      - name: Install Node Sample Dependencies
        working-directory: ./amplify-api-next
        run: npm run e2e-sandbox:install
      - name: Run e2e sandbox tests
        working-directory: ./amplify-api-next
        run: npm run e2e-sandbox:test
